[platformio]
src_dir = firmware/bascula_v4
default_envs = xiao_c6

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
  robtillaart/HX711@^0.3.9

[env:xiao_c6]
platform = espressif32
board = seeed_xiao_esp32c6

[env:xiao_s3]
platform = espressif32
board = seeed_xiao_esp32s3
